### ISSUE TITLE
Level 2 - water tower

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#12]
### Value Proposition

As a user, i want to see a new level 2, where I find out what a water tower is for and how it's built.

### Acceptance Criteria

- [x] no hydration errors
- [x] user should be guided through the process of building a water tower
- [x] on click on a specific tile, the building menu should appear
- [x] after building the tower, user should see the water disappear

### Tasks

- [x] new level2 page
- [x] display overlay telling the user how to build the tower
- [x] task: build a water tower
- [x] make the user see the process of pumping water
- [x] level win overlay should be displayed after the water has been pumped

### Sizing/Complexity

S

**Comment by actyvystom** [comment]
Hey Simon, 
please stick to the common pattern of user story value propositions: 
**As a** user,
**I want to** ...
**so that** ...

- Your acceptance criteria seem to be a bit fuzzy to me, please try to be more precise (from a user point of view)
- Your development tasks are also a bit fuzzy... as these are also your *guidelines* for development, you should write them as explicit as possible, e.g. instead of "make the user understand how it works", you could mention something like "display a hint component showing an explanation of the water tower..." or display a water tower graphic element and a bubble/hint to explain the user how it works..."
