### ISSUE TITLE
Destroy buildings

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#13]
### Value Proposition

New Card: dynamite

### Acceptance Criteria

- [x] no hydration errors
- [x] all buildings musst be destroyed and tiles return to normal

### Tasks

- [x] new level page
- [x] new card: dynamite
- [x] make the user understand how it works

### Sizing/Complexity

S
