### ISSUE TITLE
New level 5

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#14]
### Value Proposition

As a user, i want to reach a goal the game offers me. I get to know different buildings in different levels

### Acceptance Criteria

- [x] goal is understandable
- [x] game mechanics are intuitive
- [x] new level 5 playable
- [x] new objective: build a quarry

### Tasks

- [x] new level 5 db
- [x] new map
- [x] new winning condition
- [x] new card: build a quarry
- [x] new overlay with short text tutorial

### Sizing/Complexity

M
