### ISSUE TITLE
Level Page

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#15]
### Value Proposition
As a user I want to see on the level page, which levels are already played and which are unlocked/locked

### Acceptance Criteria

- [ ] played levels appear with a green hook
- [ ] locked levels are grey
- [ ] unlocked levels are displayed with color

### Tasks

- [ ] add green hook svg
- [ ] add global state for unlocking levels
- [ ] add function to display hook
- [ ] add function to make levels grey

### Sizing/Complexity

M
