### ISSUE TITLE
treasure hunt level

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#16]
### Value Proposition

As a user, I want to understand that i have to find treasures hiding under trees to solve this level. I need to use my building abilities to search and find them. When I click on them, they will be added to my inventory.

### Acceptance Criteria

- [ ] user should be able to find three treasures
- [ ] user should know how they can find them
- [ ] on click on a treasure it's displayed in the inventory
- [ ] after collecting three treasures, the level is passed

### Tasks

- [ ] new level3 page
- [ ] add a new svg treasure and implement it in the chooseImg function
- [ ] design the level tiles, so that the treasures can be found after lumbers cut certain trees down 
- [ ] display overlay telling the user how to find the treasures
- [ ] make an overlay text that explains the user how he can search for treasures
- [ ] level win overlay should be displayed after all treasures have been collected

### Sizing/Complexity

M

**Comment by stefankorder** [comment]
Hi Simon,

hydration errors are no acceptance Criteria, because you should prevent error always. Maybe you could descripe your acceptance criteria and your value proposition more detailed. What want the user? Do the user really want to find treasueres? Or do the user want to start the level and and understand what to do etc. The tasks should descripe what issues you have to solve, not what the user have to do. For example, create a new treasures object with special properties.

I hope i could help you. If you have questions anymore, just ask me.
