### ISSUE TITLE
Mobile optimization 

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#18]
### Value Proposition

Quality assurance showed some Issues with performance on safari on Iphone.
As a user I want to see a nice design on every device.

### Description
![IPhone design](https://user-images.githubusercontent.com/115007480/205860458-f21b033e-747d-4317-9587-e06d774cfb30.png)

### Acceptance Criteria

- [x] design ist shown properly on every device

### Tasks

- [x] find out what's the problem with the logo png
- [x] eventually convert it to svg
- [x] check for other styling problems on mobile devices

### Sizing/Complexity

S
