### ISSUE TITLE
New minor game mechanic changes

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#19]
### Value Proposition

As a user I want to have fun playing the game and understand what I have to do. Complex game mechanics are not understandable enough. When I see cards that explain what they do, I know that I can choose a card and what will happen.

### Acceptance Criteria

- [x] The user sees different cards with options what to do next
- [x] user can decide what cards he wants to add
- [x] cards describe what happens when you choose them

### Tasks

- [x] add card component
- [x] link component with building menu
- [x] add card db
- [x] add code to draw six cards
- [x] after stack of cards is drawn, new card is added, card stack is shuffled and drawable again

### Sizing/Complexity

L
