### ISSUE TITLE
Implement code in NextJS

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#2]
### Value Proposition

I've already created a first layout in react and try to implement it in the NextJs app

### Acceptance Criteria

- [x] no hydration errors
- [x] content should be displayed

### Tasks

- [x] implement React code in nextjs
- [x] fix the new file structure
- [x] try to make the first layout work

### Sizing/Complexity

L
