### ISSUE TITLE
New Level 1

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#23]
### Value Proposition

As a user, i want to reach a goal the game offers me. I get to know different buildings in different levels

### Acceptance Criteria

- [x] goal is understandable
- [x] game mechanics are intuitive
- [x] new level 1 playable
- [x] new objective: build a lumberhut

### Tasks

- [x] new level 1 db
- [x] new map
- [x] new winning condition
- [x] new overlay with short text tutorial

### Sizing/Complexity

M
