### ISSUE TITLE
New level 3

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#27]
### Value Proposition

As a user, i want to reach a goal the game offers me. I get to know different buildings in different levels

### Acceptance Criteria

- [x] goal is understandable
- [x] game mechanics are intuitive
- [x] new level 3 playable
- [x] new objective: upgrade a tent to a house

### Tasks

- [x] new level 3 db
- [x] new map
- [x] new winning condition
- [x] new overlay with short text tutorial

### Sizing/Complexity

S
