### ISSUE TITLE
New level 4

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#29]
### Value Proposition

As a user, i want to reach a goal the game offers me. I get to know different buildings in different levels

### Acceptance Criteria

- [x] goal is understandable
- [x] game mechanics are intuitive
- [x] new level 4 playable
- [x] new objective: build a farm

### Tasks

- [x] new level 4 db
- [x] new map
- [x] new winning condition
- [x] new card: farm
- [x] implement functional dependency between wells and farms
- [x] new overlay with short text tutorial

### Sizing/Complexity

M
