### ISSUE TITLE
Level Structure

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#3]
### Value Proposition

I need to organize a level structure for my App, so that each level can load a map individually.

### Acceptance Criteria
- [x] No hydration errors
- [x] no vercel errors

### Tasks

- [x] make way for the new level structure
- [x] new levels should be new pages
- [x] each level needs an own level db
- [x] main menu page
- [x] main menu buttons
