### ISSUE TITLE
Tutorial 2.0

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#33]
### Value Proposition

As a user, I need to understand how the game works before I start it. 

### Acceptance Criteria

- [x] When you start the game, a detailed tutorial pops up.
- [x] Every mechanic is explained before the game starts.

### Tasks

- [x] new state option for the big overlay
- [x] pages with screenshot imgs and text
- [x] after last page, overlay disappears again

### Sizing/Complexity

**S / M / L**
