### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#4]
### Value Proposition

It's finally time to add some functionality! I'll start with a tutorial.

### Acceptance Criteria

- [x] working tutorial from beginning to the end
- [x] no reload bugs
- [x] no hydration errors

### Tasks

- [x] make a tutorial
- [x] each building should be explained
- [x] each step should display a new overlay
- [x] change tasks
- [x] winning condition
- [x] losing condition

### Sizing/Complexity

L
