### ISSUE TITLE
save and load

### ISSUE THREAD

**Issue by B4CKSL4SH-44** [simon-schuster44/Capstone-Tropicolony#5]
### Value Proposition

As a user, I want to save and load my game, when I do not have the time to finish the level.

### Acceptance Criteria

- [x] In every Level, you have the option to save your game at any time
- [x] when you load a game from the menu, the game page loads with the saved map and resources

### Tasks

- [x] add local storage custom hook
- [x] add save function for each page
- [x] add loading function from main menu
- [x] add function to switch to the right level page and load data

### Sizing/Complexity

L
